### ISSUE TITLE
MAC address seems to be persisted to SD card

### ISSUE THREAD

**Issue by aadavids** [nerves-project/nerves_system_bbb#151] opened 2020-06-10 20:36 UTC
### Environment

* Elixir version (`elixir -v`):
```
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 22)
```
* Nerves environment: (`mix nerves.env --info`)
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_bbb
  Vsn:         2.6.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.11.4
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   bbb
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     bbb
  toolchain:  /home/andrew/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.3.2
  system:     /home/andrew/.nerves/artifacts/nerves_system_bbb-portable-2.6.2
  app:        /home/andrew/repos/hello_nerves

|nerves_bootstrap| Loadpaths End

```
* Additional information about your host, target hardware or environment that
  may help

I've tested this with both the current "hello_nerves" project (mix nerves.new hello_nerves), and an older one that used init_gadget instead of nerves_pack.

### Current behavior
So this might be a strange one. I'm not sure if this is desired behaviour or not, but it seems like the Ethernet MAC is getting persisted to the SD card. I've tested this with projects using init_gadget and nerves_pack, so I don't think the issue is in the networking libraries (or they both have the same behaviour).

Take two Beaglebone Blacks. Burn hello nerves project onto SD card.

Insert SD card into BBB 1. MAC address is correctly reported. Move SD card to BBB 2. MAC address is that of BBB 1.

Re-burn the project to the SD card. Insert into BBB2. MAC address is correct. But when moved to BBB1, the MAC address reported is that of BBB2.

### Expected behavior
MAC address is correctly reported.
I also tested an sd card with debian, and it seems to work as expected.

**Comment by fhunleth** [comment] 2020-06-11 15:53
Ok, I can confirm. This is due to the `saveenv` call from the auto-revert U-Boot script. U-Boot doesn't differentiate between temporary and permanent variables. The automatically found MAC address was being saved because of that `saveenv` call. Then it appears that on the next boot, U-Boot chooses to use mac addresses saved in its environment block over automatically found ones. (This seems logical if you want to override a MAC address.)  Unfortunately, this means that the automatically detected MAC address is saved to the MicroSD card and that value overrides the real one if you move MicroSD cards around.

Investigating workarounds...

**Comment by fhunleth** [comment] 2020-06-11 16:04
Quick workaround to fix this after moving a MicroSD card between boards:

```
iex> cmd("fw_setenv ethaddr")
iex> reboot
```

There are other variables with this problem: board type and serial number. At the moment, it doesn't look like U-Boot provides any mechanism to deal with this issue.

**Comment by aadavids** [comment] 2020-06-11 20:47
Thanks for looking into it! That's interesting. I should be able to work around it for now.

It was mostly an issue on our custom boards that were using the ethernet MAC as a serial number. But normally we run off the EMMC, so the issue only popped up with a small nerves project I wrote that ran off the SD Card to do some validation of our custom board and to automate burning the nerves image onto the EMMC.

**Comment by fhunleth** [comment] 2020-06-11 21:31
I'm glad that this works for you. I don't like any of the fixes that I can think of right now. The note and workaround is the best that I could do today.

Thanks for posting the issue. I've worked with U-Boot for a long time and had never appreciated that `saveenv` would have the side effect of caching the MAC address. It makes a lot of sense now.

Since `saveenv` is only called in the U-Boot script after firmware updates. Clearing `ethaddr` should stick until the next update. In fact, if you wanted to delete the calls to `saveenv` in the boot script for your loader, that would work too. I think that's unnecessary, though.

I'm going to close this issue. If the workaround stops working for you, please re-open.

**Closed by fhunleth** 2020-06-11 21:31 UTC
